### ISSUE TITLE
Feedback for "Privileges and Permissions"

### ISSUE THREAD

**Issue by MartinSautterAnalytics4you** [SAP-docs/sap-datasphere#10]
https://help.sap.com/docs/SAP_DATASPHERE/9f804b8efa8043539289f42f372c4862/d7350c6823a14733a7a5727bad8371aa.html?locale=en-US

alphabetic order of the permissons or the order of the Menue.

**Comment by CindyVenet** [comment]
Dear SAP Datasphere user

By default, the privileges are not sorted by alphabetical order, neither by their order in the user interface. You can simply click the column header to sort them by alphabetical order.

Thank you very much. We are having a look at your other comments and will provide feedback soon (some of them need to be checked with our experts)

Best regards
Cindy
