### ISSUE TITLE
Feedback for "Standard Application Roles"

### ISSUE THREAD

**Issue by MartinSautterAnalytics4you** [SAP-docs/sap-datasphere#12]
https://help.sap.com/docs/SAP_DATASPHERE/9f804b8efa8043539289f42f372c4862/a50a51d80d5746c9b805a2aacbb7e4ee.html?locale=en-US

Explain: How to limit a User to have only access to a certain or several  Dataspehre Space(s) ?

**Comment by CindyVenet** [comment]
Dear SAP Datasphere User

This topic lists all the standard roles and we have indicated that a user can access a space of which he/she is a member of.  To assign a member to a space, it's explained here: https://help.sap.com/docs/SAP_DATASPHERE/be5967d099974c69b77f4549425ca4c0/9d59fe511ae644d98384897443054c16.html

We will just add a link to this topic.

Thank you and best regards
Cindy

**Comment by MartinSautterAnalytics4you** [comment]
Nice, Thank You,
