### ISSUE TITLE
Wrong error code for "Proxy server connect: Network unreachable"

### ISSUE THREAD

**Issue by hjkim0522** [SAP-docs/sap-datasphere#17]
### Issue description

5. The selected location ID is invalid.
```
[LIBODBCHDB SO][HDBODBC] Communication link failure;-10709 Connection failed (RTE:[89132] 
Proxy server connect: Network unreachable (<virtual_host>:<virtual_port>))
```
The error code listed in section 5 should be 89133 instead of 89132. That's the code HANA is returning for "Network unreachable" error.

6 and 7 is using correct error code, 89133, but 5 looks like a mistake.

### Feedback Type (Optional)

None

### Page Title on SAP Help Portal (prefilled)

Troubleshooting SAP HANA Smart Data Access via Cloud Connector

### Page URL on SAP Help Portal (prefilled)

https://help.sap.com/docs/SAP_DATASPHERE/9f804b8efa8043539289f42f372c4862/42f683edbf6742b19cf15e7a18b8a607.html?locale=en-US

**Comment by hjkim0522** [comment]
https://people.sap.com/hyunjunkim

**Comment by co-sti** [comment]
Dear Hyunjun Kim, 

you can see the correction in the internal draft version: https://help.sap.com/docs/SAP_DATASPHERE/9f804b8efa8043539289f42f372c4862/42f683edbf6742b19cf15e7a18b8a607.html?state=DRAFT&version=DEV. The change will be published externally for customers with wave version 2023.20.

Thank you and best Regards,
Cornelia

**Comment by hjkim0522** [comment]
It looks very good, thank you for taking care of it.
