### ISSUE TITLE
Missing Inforamtion

### ISSUE THREAD

**Issue by Sebastian-Haase-SAP** [SAP-docs/sap-datasphere#18]
### Issue description

Data Flow Section is missleading with reagards to support of CDS Views.
- CDS Views are available for the OnPremise connection but the text reads as if they were only available in S/4HANA Cloud

Replicaiton Flow Section is completely missing CDS Views.
Replication Flow Section is missing the aspect what is supported for S/4HANA Cloud vs. S/4HANA OnPremise.

### Feedback Type (Optional)

content gaps

### Page Title on SAP Help Portal (prefilled)

SAP ABAP Connections

### Page URL on SAP Help Portal (prefilled)

https://help.sap.com/docs/SAP_DATASPHERE/be5967d099974c69b77f4549425ca4c0/a75c1aacf951449ba3b740c7e46da3a9.html

**Comment by co-sti** [comment]
Dear Sebastian,
thanks for your feedback. I'm working on it and will send a draft version for a review.
Best Regards,
Conny

**Comment by co-sti** [comment]
Hello Sebastian,
the required changes have been incorporated [here](https://help.sap.com/docs/SAP_DATASPHERE/be5967d099974c69b77f4549425ca4c0/a75c1aacf951449ba3b740c7e46da3a9.html) quite some time ago.
For CDS views supporting data flows, a link to S/4 op has been added to indicate that also op is supported, and the replication flow section has been enhanced, so I'm closing this issue.
Thank you for your feedback.
Best Regards,
Cornelia (for the UA team)
