### ISSUE TITLE
Information missing

### ISSUE THREAD

**Issue by Sebastian-Haase-SAP** [SAP-docs/sap-datasphere#20]
### Issue description

Supported Features - Data Flows (e.g. compare with ABAP Connection):
- "source objects" not speficied => it should be CDS Views
- missing C1 informaiton on available views
- missing note that only initial load is possible
- missing link to S/4HANA docu on communication scenario

Supported Features - Replication Flows:
- "source objects" not speficied => it should be CDS Views
- missing C1 informaiton on available views
- missing link to S/4HANA docu on communication scenario

### Feedback Type (Optional)

content gaps

### Page Title on SAP Help Portal (prefilled)

SAP S/4HANA Cloud Connections

### Page URL on SAP Help Portal (prefilled)

https://help.sap.com/docs/SAP_DATASPHERE/be5967d099974c69b77f4549425ca4c0/a98e5ffdf47c44d9a845dca01a18bd82.html

**Comment by co-sti** [comment]
Dear Sebastian,
thanks for your feedback. I'm working on it and will send a draft version for a review.
Best Regards,
Conny

**Comment by co-sti** [comment]
Hello @Sebastian-Haase-SAP ,

can you please check if the changes in the "Features" section of the SAP S/4HANA Cloud topic fix the issues you mentioned above for data and replication flows: https://help.sap.com/docs/SAP_DATASPHERE/be5967d099974c69b77f4549425ca4c0/a98e5ffdf47c44d9a845dca01a18bd82.html?state=DRAFT&version=DEV

Please let me know if there is some important information missing or if there is something wrong or misleading.

Regarding missing links to the required communication scenarios/arrangements, this information is kept in the connection preparation topic here and there is only a link to the prerequisites from the connection type topic (it is available in the upper part of the topic directly before the "Supported Features" section: https://help.sap.com/docs/SAP_DATASPHERE/9f804b8efa8043539289f42f372c4862/abb159e027184c98a54fc1b2a88dd3f5.html?state=DRAFT&version=DEV.
If the link is too hidden, I can think of mention it more prominently, e.g. in a separate section "Prerequisites".

Thanks and best Regards,
Conny

**Comment by Sebastian-Haase-SAP** [comment]
I see you also added the SQL Service which I forgot to mention above - thank you for double checking!
It looks good to me - just having the link in the top is fine. Let's wait for customer feedback on it.
