### ISSUE TITLE
Update needed on "Data Flows and Replication Flows" section

### ISSUE THREAD

**Issue by Sebastian-Haase-SAP** [SAP-docs/sap-datasphere#21]
### Issue description

Communication scenario name outdated
Communication scenario is needed for both, data flow and replication flow - right now it reads as if it was only necessary for data flow
"For replication flows, CDS view replication is supported for SAP S/4HANA Cloud version 2202 and higher." => correct but no longer releveant as we have out upgrades in cloud.

### Feedback Type (Optional)

content gaps

### Page Title on SAP Help Portal (prefilled)

Prepare Connectivity to SAP S/4HANA Cloud

### Page URL on SAP Help Portal (prefilled)

https://help.sap.com/docs/SAP_DATASPHERE/9f804b8efa8043539289f42f372c4862/abb159e027184c98a54fc1b2a88dd3f5.html?locale=en-US&state=PRODUCTION&version=cloud

**Comment by co-sti** [comment]
Hello @Sebastian-Haase-SAP ,

can you please check if the changes in the S/4HANA Cloud preparation topic fix the issues you mentioned above for data and replication flows: https://help.sap.com/docs/SAP_DATASPHERE/9f804b8efa8043539289f42f372c4862/abb159e027184c98a54fc1b2a88dd3f5.html?state=DRAFT&version=DEV? 

The changes also reflect replication via SQL services.

Please let me know if there is some important information missing or if there is something wrong or misleading. I haven't pointed to SAP Note 2890171 from here, but can do so in a separate bullet point if required.

Thanks and best Regards,
Conny

**Comment by Sebastian-Haase-SAP** [comment]
Hi Conny,

looks good to me - thank you for the changes.

A minor aspect on the wording in the replication flows section (not sure whether intended):
In the SQL services section, it mentions that the administrator has created the communication arrangements. In the section on CDS views, it is just created (without specifying who did it). This pattern - sometimes with administrator, sometimes without - is present also e.g. for remote tables.

Best regards,
Sebastian
