### ISSUE TITLE
Data Flow Section incomplete

### ISSUE THREAD

**Issue by Sebastian-Haase-SAP** [SAP-docs/sap-datasphere#22]
### Issue description

Information on available objects missing (compare e.g. to ABAP or S/4HANA Cloud Connection)

### Feedback Type (Optional)

content gaps

### Page Title on SAP Help Portal (prefilled)

SAP S/4HANA On-Premise Connections

### Page URL on SAP Help Portal (prefilled)

https://help.sap.com/docs/SAP_DATASPHERE/be5967d099974c69b77f4549425ca4c0/a49a1e3cc50f4af89711d8306bdd8f26.html

**Comment by co-sti** [comment]
Hello @Sebastian-Haase-SAP ,

can you please check if the changes in the "Features" section of the SAP S/4HANA topic fix the issues you mentioned above for data and replication flows: https://help.sap.com/docs/SAP_DATASPHERE/be5967d099974c69b77f4549425ca4c0/a49a1e3cc50f4af89711d8306bdd8f26.html?state=DRAFT&version=DEV

I've revised the information for both, data flows and replication flows. Please let me know if there is some important information missing or if there is something wrong or misleading.

Thanks and best Regards,
Conny
