### ISSUE TITLE
Prerequisites Outdated

### ISSUE THREAD

**Issue by Sebastian-Haase-SAP** [SAP-docs/sap-datasphere#23]
### Issue description

For Data Flows and Replication Flows the listed prerequisites are outdated. I think it would be best to just reference SAP note 2890171 and state that systems should be fully patched,

### Feedback Type (Optional)

clarity

### Page Title on SAP Help Portal (prefilled)

Prepare Connectivity to SAP S/4HANA On-Premise

### Page URL on SAP Help Portal (prefilled)

https://help.sap.com/docs/SAP_DATASPHERE/9f804b8efa8043539289f42f372c4862/8de01dd25c1e443e8e2de7d2fbe1364d.html

**Comment by co-sti** [comment]
Dear Sebastian,
thanks for your feedback. I'm working on it and will send a draft version for a review.
Best Regards,
Conny

**Comment by co-sti** [comment]
Hi @Sebastian-Haase-SAP ,

in the prerequisites sections for data flows and replication flows, I've now mainly kept some Cloud Connector information and links + the disclaimer about minimum requirement for source versions  incl. the link to SAP Note https://me.sap.com/notes/2890171.

Please let me know if there is some important information missing or if there is something wrong or misleading.

Thanks and best Regards,
Conny

**Comment by Sebastian-Haase-SAP** [comment]
Looks very good - thank you!
