### ISSUE TITLE
URL not available for help on Datasphere for new connection for Google Big Query

### ISSUE THREAD

**Issue by andreasdietzberatungscontorde** [SAP-docs/sap-datasphere#24]
### Issue description

Hello, 

I tried to establish a new datasphere connection for Google Big Query. The connection works but the help cannot be found. See https://help.sap.com/docs/page-not-found?url=https%3A%2F%2Fhelp.sap.com%2Fhttp.svc%2Foutputlink%3Fproductname%3DSAP_DATASPHERE%26projectname%3DDWC%25202023.24%2520-%2520In-App%2520Help%26deliverable%3De9275e9c7684454f9cf8b7c687848c64%26version%3D2023.24%26language%3Dde-DE%26state%3DPRODUCTION%26filepath%3Db9b5579054df48c39381d5b17286bf21.html%26transtype%3Dxhtml.body%26buildablemaploio%3D%26projectphio%3Dkat1696319849513%26dependantprojects%3Defa1696319835071%26source%3Dproductlink-webassistant

Best regards

### Feedback Type (Optional)

content gaps

### Page Title on SAP Help Portal (prefilled)

Upload Third-Party ODBC Drivers (Required for Data Flows)

### Page URL on SAP Help Portal (prefilled)

https://help.sap.com/docs/SAP_DATASPHERE/9f804b8efa8043539289f42f372c4862/b9b5579054df48c39381d5b17286bf21.html?locale=en-US

**Comment by co-sti** [comment]
Dear customer, 
thank you for your feedback. We're investigating the issue and will get back to you soon.
Best Regards,
the SAP Datasphere User Assistance team

**Comment by co-sti** [comment]
Dear customer, 

the in-app help for Google Big Query connections has been revised. All links to Help Portal documentation should work. There is no direct link to https://help.sap.com/docs/SAP_DATASPHERE/9f804b8efa8043539289f42f372c4862/b9b5579054df48c39381d5b17286bf21.html?locale=en-US anymore but to the overall prerequisites described in https://help.sap.com/docs/SAP_DATASPHERE/9f804b8efa8043539289f42f372c4862/529cef1eee6a45a69ae4e51951718900.html

![image](https://github.com/SAP-docs/sap-datasphere/assets/121945222/926f0c18-0c03-428b-8eaa-bb92c9330d0a)

Thanks again for your feedback.
Best Regards,
the SAP Datasphere User Assistance team
