### ISSUE TITLE
Connect BigQuery with region location with datasphere

### ISSUE THREAD

**Issue by Alebas-Ribeiro** [SAP-docs/sap-datasphere#25]
### Issue description

Hello Guys,
 
I had a issue in a customer environment using big query for replication flow.
 
In a documentation , we assume that location is optional. (Image 1)

<img width="669" alt="image1" src="https://github.com/SAP-docs/sap-datasphere/assets/153555019/f946f696-3147-4888-bdc6-9f56fe057be7">

 This customer had a big query in region location.
 
when we tried to connect in replication flow, the dataset is not loaded. (Image 2)

<img width="734" alt="image2" src="https://github.com/SAP-docs/sap-datasphere/assets/153555019/58feded6-507d-465e-bdf6-831d8547494c">

 If I fill the location (in my case us-east1), the dataset from Big query load normally. (Image 3)
 
<img width="724" alt="image3" src="https://github.com/SAP-docs/sap-datasphere/assets/153555019/affc01d4-b521-438e-af93-c37c2398bf79">

If its possible, we need to add this in the help documentation :
 
"When Google Bigquery dataset was create using region mode it’s necessary fill the location."
 

Cheers
Alebas

### Feedback Type (Optional)

None

### Page Title on SAP Help Portal (prefilled)

Prepare Connectivity to Google BigQuery

### Page URL on SAP Help Portal (prefilled)

https://help.sap.com/docs/SAP_DATASPHERE/9f804b8efa8043539289f42f372c4862/529cef1eee6a45a69ae4e51951718900.html?version=cloud

**Comment by co-sti** [comment]
Dear Alebas,
thanks a lot for your feedback. I'll follow up on updating the documentation to improve the misleading part and let you know once done.
Best Regards,
Cornelia from the SAP Datasphere User Assistance team

**Comment by Alebas-Ribeiro** [comment]
https://people.sap.com/ale.ribeiro

From: sap-doc-bot[bot] ***@***.***>
Date: Tuesday, 12 December 2023 at 04:38
To: SAP-docs/sap-datasphere ***@***.***>
Cc: Ribeiro, Alexandre ***@***.***>, Mention ***@***.***>
Subject: Re: [SAP-docs/sap-datasphere] Connect BigQuery with region location with datasphere (Issue #25)
You don't often get email from ***@***.*** Learn why this is important<https://aka.ms/LearnAboutSenderIdentification>

Thank you for your valuable feedback contribution, @Alebas-Ribeiro<https://github.com/Alebas-Ribeiro>! So that we can recognize your contribution in SAP Community<https://github.com/SAP-docs/contribution-guidelines/blob/main/docs/recognition.md>, please tell us your SAP Community profile URL in a reply to this comment; don't include any other text, just the URL on its own, like this:

https://people.sap.com/your-user-name

Thanks!

**Comment by co-sti** [comment]
Hi Alebas,

with 2024.02, the documentation for the Google BigQuery property "Location" will change to the following to make clear that datasets from any other than the default location are only available if the location is added in the connection configuration:

"[optional] Enter an additional location. By default, SAP Datasphere connects to BigQuery datasets only from Google's default location - US. Datasets from any other location will only be available in the Data Builder if you enter the additional location here. 
A location can be a region, for example us-west1or asia-east1, or a multi-region, for example EU. 
Note: If you provide an invalid location, the connection validation still passes, but failures will happen when you're using the connection in the Data Builder."

Thanks a lot for contributing to this documentation improvement.

Best Regards,
Cornelia from the SAP Datasphere User Assistance team

**Comment by co-sti** [comment]
I'm closing this issue since the correction is available in the 2024.02 version of the documentation.
