### ISSUE TITLE
spelling mistakes in several places

### ISSUE THREAD

**Issue by condamoor-sap** [SAP-docs/sap-datasphere#26]
### Feedback Type (Optional)

None

### Page Title on SAP Help Portal (prefilled)

Configure the Size of Your SAP Datasphere Tenant

### Page URL on SAP Help Portal (prefilled)

https://help.sap.com/docs/SAP_DATASPHERE/9f804b8efa8043539289f42f372c4862/33f8ef4ec359409fb75925a68c23ebc3.html?q=sac%20integration

**Comment by condamoor-sap** [comment]
Under the Data Integration section....

**Comment by CindyVenet** [comment]
Dear SAP Datasphere User

Thank you very much for your feedback. We are having a look at the issues.
We'll keep you informed
 
Best regards
Cindy Venet

**Comment by condamoor-sap** [comment]
https://people.sap.com/condamoor

**Comment by CindyVenet** [comment]
Dear User

The spelling mistakes have been corrected for the current wave in development process (wave 03).

Thank you very much for your feedback and ... Merry Xmas !

Best regards
Cindy for the UA team
