### ISSUE TITLE
In Premiu Outbound Integration section

### ISSUE THREAD

**Issue by condamoor-sap** [SAP-docs/sap-datasphere#27]
### Issue description

Need to define the relationship between Blocks and GB. Not too useful otherwise.

### Feedback Type (Optional)

None

### Page Title on SAP Help Portal (prefilled)

Configure the Size of Your SAP Datasphere Tenant

### Page URL on SAP Help Portal (prefilled)

https://help.sap.com/docs/SAP_DATASPHERE/9f804b8efa8043539289f42f372c4862/33f8ef4ec359409fb75925a68c23ebc3.html?q=sac%20integration

**Comment by CindyVenet** [comment]
Dear SAP Datasphere user

Thank you for your feedback. We are working to improve the content and will come back to you soon

Best regards
Cindy for the User assistance Team

**Comment by theresa-sanchez** [comment]
Dear SAP Datasphere User,

The help has been updated in the wave 2024.03 version of the help. Each block = 20 GB.

Best regards,
Theresa from User Assistance
