### ISSUE TITLE
Add better instructions guidance for certificate download.

### ISSUE THREAD

**Issue by ismael-cardoso** [SAP-docs/sap-datasphere#28]
### Issue description

Could resolution of KBA be included here?
3424000 - SAP Datasphere issue with BQ Google Connection

open https://cloud.google.com/ and export the GTS Root R1 certificate which is valid until 2036.

Once done, KBA can be archived. 

### Feedback Type (Optional)

examples or samples

### Page Title on SAP Help Portal (prefilled)

Upload Certificates (Required for Remote Tables)

### Page URL on SAP Help Portal (prefilled)

https://help.sap.com/docs/SAP_DATASPHERE/9f804b8efa8043539289f42f372c4862/46f5467adc5242deb1f6b68083e72994.html?version=cloud

**Comment by co-sti** [comment]
Dear Ismael, thank you for your feedback.
We are currently revising the certificate documentation for SAP Datasphere and I will reflect your feedback and let you know once done by the end of next week.
Best Regards,
Conny from the UA team

**Comment by co-sti** [comment]
Hello Ismael,
the requested information is available in the GBQ prerequisites documentation [here](https://help.sap.com/docs/SAP_DATASPHERE/9f804b8efa8043539289f42f372c4862/529cef1eee6a45a69ae4e51951718900.html). After internal discussions, we decided to keep the [Manage Certificates for Connections documentation](https://help.sap.com/docs/SAP_DATASPHERE/9f804b8efa8043539289f42f372c4862/46f5467adc5242deb1f6b68083e72994.html) general and keep specific information in the connection type specific prerequisites docs.
Thanks a lot for your feedback.
Best Regards,
Conny (from the UA team)
