### ISSUE TITLE
Missing info

### ISSUE THREAD

**Issue by NikhilD16** [SAP-docs/sap-datasphere#29]
### Issue description

To modify the throughput of the target that is missing, refer to source documentation. https://help.sap.com/docs/SAP_DATASPHERE/c8a54ee704e94e15926551293243fd1d/749638060e8746e48b0f9bf0e50c6d0c.html
Also, we need to mention SAP's recommendation that source and target threads should be the same, to have consistent throughput.  

### Feedback Type (Optional)

outdated information

### Page Title on SAP Help Portal (prefilled)

Add a Target

### Page URL on SAP Help Portal (prefilled)

https://help.sap.com/docs/SAP_DATASPHERE/c8a54ee704e94e15926551293243fd1d/ab490fb4d083442197e2ba3b92079734.html

**Comment by CindyVenet** [comment]
Dear SAP Datasphere user
We are looking at the issue and will provide feedback soon
thank you for your feedback
best regards
Cindy for the UA team

**Comment by NikhilD16** [comment]
Do you what's the ETA here?

**Comment by CindyVenet** [comment]
Dear SAP Datasphere user

The issue has been corrected with wave 04  that was delivered on wave 04. Please check the documentation [https://help.sap.com/docs/SAP_DATASPHERE/c8a54ee704e94e15926551293243fd1d/749638060e8746e48b0f9bf0e50c6d0c.html?locale=en-US](url) and let us know if something is still missing from your side.

Sorry I am not sure what you mean by ETA?

Thank you and best regards
Cindy for the UA team
