### ISSUE TITLE
Include additional information about clean up

### ISSUE THREAD

**Issue by ismael-cardoso** [SAP-docs/sap-datasphere#30]
### Issue description

Role “DW Administrator” has privilege "Activity Log" by default as “Read” = enabled and Permission “Delete” = disabled.
Therefore to delete the activity log with the user that has role "System Owner". 

Please include this info in the page.

BR.

### Feedback Type (Optional)

content gaps

### Page Title on SAP Help Portal (prefilled)

Monitor Object Changes with Activities

### Page URL on SAP Help Portal (prefilled)

https://help.sap.com/docs/SAP_DATASPHERE/9f804b8efa8043539289f42f372c4862/08e607c58e5343bd9c0287e7e22c452a.html?locale=en-US&version=cloud

**Comment by CindyVenet** [comment]
Dear SAP Datasphere User

thank you for your feedback. We are working on it and will provide an answer soon
best regards
Cindy for the UA team

**Comment by CindyVenet** [comment]
Dear SAP Datasphere User

Thanks for your valuable feedback.

The permission “Delete” for the privilege “Activity Log” is not included in the DW Administrator role. To delete the activity log for a specific time period, you need to be a system owner or you can also be assigned to a custom role that grants the “Delete” permission. To do so, you can create a custom role based on the DW Administrator template, check the “Delete” permission for the privilege “Activity Log”, then assign a user to this custom role.

We’ve amended the documentation accordingly, which will be available in version 2024.06 on the SAP Help Portal.

Best regards, 
The UA Team
