### ISSUE TITLE
Memory (GB) information provided

### ISSUE THREAD

**Issue by LucimarM** [SAP-docs/sap-datasphere#31]
### Issue description

It is not possible to add more memory than disk. This information is not mention there, so customers will not able able to add more memory without increasing the disk. Could you mention this info there?

### Feedback Type (Optional)

None

### Page Title on SAP Help Portal (prefilled)

Allocate Storage to a Space

### Page URL on SAP Help Portal (prefilled)

https://help.sap.com/docs/SAP_DATASPHERE/9f804b8efa8043539289f42f372c4862/f414c3d62bfe49b38e2cfdd7b4e7d786.html?locale=en-US&q=spage%20quota

**Comment by CindyVenet** [comment]
Dear SAP Datasphere User

thank you for your feedback. We are working on it and will provide an answer soon
best regards
Cindy for the UA team

**Comment by CindyVenet** [comment]
dear SAP Datasphere User

Thanks for your valuable feedback.

We’ve amended the documentation accordingly, mentioning that it is not possible to allocate more memory than disk. The documentation update will be available in version 2024.06 on the SAP Help Portal.

Best regards, 
The UA Team
