### ISSUE TITLE
Example data after applying data access control is incorrect.

### ISSUE THREAD

**Issue by UDUPAD** [SAP-docs/sap-datasphere#32]
### Issue description

The output data displayed after data access control is applied is shown as bob - Paris. It has to be ann – Paris based on the Geo permissions and hierarchy tables shared.
	bob - Europe, France, or Paris.
	jim - France or Paris.
	**bob - Paris.**

### Feedback Type (Optional)

examples or samples

### Page Title on SAP Help Portal (prefilled)

Create a "Hierarchy" Data Access Control

### Page URL on SAP Help Portal (prefilled)

https://help.sap.com/docs/SAP_DATASPHERE/be5967d099974c69b77f4549425ca4c0/0afeeed6b56a40f5a02581032ec39420.html?q=data%20access%20control

**Comment by CindyVenet** [comment]
Dear SAP Datasphere User

Thank you for your feedback. We are working on your issue and will come back to you with a solution.

best regards
Cindy for the UA team

**Comment by CindyVenet** [comment]
Dear SAP Datasphere User

the issue has been fixed in the documentation and will be available with wave 05 

thank you and best regards
Cindy for the UA team

**Comment by UDUPAD** [comment]
> Thank you for your valuable feedback contribution, @UDUPAD! So that we can [recognize your contribution in SAP Community](https://github.com/SAP-docs/contribution-guidelines/blob/main/docs/recognition.md), please tell us your SAP Community profile URL in a reply to this comment; don't include any other text, just the URL on its own, like this:
> 
> ```
> https://people.sap.com/your-user-name
> ```
> 
> Thanks!

https://community.sap.com/t5/user/viewprofilepage/user-id/1402306
