### ISSUE TITLE
Replication Thread Limit

### ISSUE THREAD

**Issue by NikhilD16** [SAP-docs/sap-datasphere#33]
### Issue description

The Replication Thread Limit needs to be reworded to update the information from the blog 
https://community.sap.com/t5/technology-blogs-by-sap/replication-flow-blog-series-part-4-sizing/ba-p/13579486

Refer to the internal bug 

### Feedback Type (Optional)

None

### Page Title on SAP Help Portal (prefilled)

Configure Your Replication Flow

### Page URL on SAP Help Portal (prefilled)

https://help.sap.com/docs/SAP_DATASPHERE/c8a54ee704e94e15926551293243fd1d/3f5ba0c5ae3944c1b7279bb989a2a5b5.html?q=replication&version=cloud

**Comment by CindyVenet** [comment]
Dear User

we are working on the issue and will come back with a solution soon. 

best regards
Cindy for the UA team

**Comment by CindyVenet** [comment]
Dear User

the documentation has been enhanced with information on thread limits: see https://help.sap.com/docs/SAP_DATASPHERE/c8a54ee704e94e15926551293243fd1d/3f5ba0c5ae3944c1b7279bb989a2a5b5.html?q=replication 
Thank you for your feedback
best regards
Cindy for the UA team
