### ISSUE TITLE
Cloud connector is not relevant for Fieldglass

### ISSUE THREAD

**Issue by ismael-cardoso** [SAP-docs/sap-datasphere#38]
### Issue description

Data Flows section should be reviewed/removed. This is not relevant for SAP Fieldglass. 

### Feedback Type (Optional)

None

### Page Title on SAP Help Portal (prefilled)

Prepare Connectivity to SAP Fieldglass

### Page URL on SAP Help Portal (prefilled)

https://help.sap.com/docs/SAP_DATASPHERE/9f804b8efa8043539289f42f372c4862/03ca23660b5d4b69960f264f5c31990e.html?locale=en-US&version=cloud

**Comment by co-sti** [comment]
Hello Ismael,
thanks a lot for the feedback. I'll let you know as soon as the changes are done.
Best Regards,
Conny (SAP Datasphere UA team)

**Comment by co-sti** [comment]
Hello @ismael-cardoso , 

I have made the changes for 2024.07 version for SAP Fieldglass and SAP Marketing Cloud, too. CDI connection configuration, however, still contains Cloud Connector. 
You can find the changes here:
SAP Fieldglass connection:
Prepare SAP Fieldglass connectivity: https://help.sap.com/docs/SAP_DATASPHERE/be5967d099974c69b77f4549425ca4c0/bda94ee6c9d5403f8556af174399d221.html?state=DRAFT&version=DEVhttps://help.sap.com/docs/SAP_DATASPHERE/9f804b8efa8043539289f42f372c4862/03ca23660b5d4b69960f264f5c31990e.html?state=DRAFT&version=DEV
SAP Marketing Cloud connection: https://help.sap.com/docs/SAP_DATASPHERE/be5967d099974c69b77f4549425ca4c0/4de4959620c24d12a53a3cc357d3e003.html?state=DRAFT&version=DEV
Prepare SAP Marketing Cloud connectivity: https://help.sap.com/docs/SAP_DATASPHERE/9f804b8efa8043539289f42f372c4862/f5e0c06fdc834c62a10eeb19d9a79bab.html?state=DRAFT&version=DEV

Thanks again for your feedback.
Best Regards,
Conny
