### ISSUE TITLE
PRIV "Catalog KPI Object" is not available on Datasphere

### ISSUE THREAD

**Issue by akarimb007** [SAP-docs/sap-datasphere#39]
### Issue description

Privelege "Catalog KPI Object" is not available when creating a Custom role on Datasphere.

### Feedback Type (Optional)

None

### Page Title on SAP Help Portal (prefilled)

Privileges and Permissions

### Page URL on SAP Help Portal (prefilled)

https://help.sap.com/docs/SAP_DATASPHERE/9f804b8efa8043539289f42f372c4862/d7350c6823a14733a7a5727bad8371aa.html

**Comment by akarimb007** [comment]
Also, Privelege  "Catalog KPI Template " is not available when creating a custom role on Datasphere

**Comment by CindyVenet** [comment]
Dear SAP Datasphere User

thank you for your feedback. We are working on the issue and will provide an answer soon
 Best regards
Cindy for the UA team

**Comment by CindyVenet** [comment]
Dear SAP Datasphere User
We've done some tests and we were able to include the following privileges in a custom role: "Catalog KPI Object" and "Catalog KPI Template". Could you please tell us more about the steps you've followed? 
Thanks in advance.
Best regards
Cindy for the UA team

**Comment by akarimb007** [comment]
Hello team,

Jahr Silke from SAP has informed me that there was a bug which has been recently fixed.

The issue can be closed.

Thanks
Anu
