### ISSUE TITLE
Important fact about "Deployment after import

### ISSUE THREAD

**Issue by ismael-cardoso** [SAP-docs/sap-datasphere#40]
### Issue description

Please include a "Note!" to aware customers that if they want to deploy objects by importing process (option "deploy after import"), they need to consider the deployment order of objects with dependencies. For example, the source object must be deployed firstly, then to share it to target space.

### Feedback Type (Optional)

None

### Page Title on SAP Help Portal (prefilled)

Importing Content from Another Tenant

### Page URL on SAP Help Portal (prefilled)

https://help.sap.com/docs/SAP_DATASPHERE/be5967d099974c69b77f4549425ca4c0/b607a12931d74c4a93506ea64c55ab4e.html?locale=en-US&version=cloud

**Comment by CindyVenet** [comment]
Dear SAP Datasphere User

Your feedback is received and we are working on it. We'll let you know once a solution is available

best regards
Cindy for the UA team

**Comment by CindyVenet** [comment]
Dear User

The note will be available with wave 09
![image](https://github.com/SAP-docs/sap-datasphere/assets/117640545/28f8933e-78e1-4d2f-a3ad-08f2d29ecc77)

Thank you for your contribution
best regards
Cindy for the UA team
