### ISSUE TITLE
Local Tables

### ISSUE THREAD

**Issue by LucimarM** [SAP-docs/sap-datasphere#42]
### Issue description

In the "Local Tables", please add the information that data is not exported. See https://jira.tools.sap/browse/DW101-45400

"
Transport of Local Table data is not supported for Datasphere.

Here is the documentation: https://help.sap.com/docs/SAP_DATASPHERE/be5967d099974c69b77f4549425ca4c0/44e775c3b7d24d2483caaf02c598bc21.html?locale=en-US

It says: "The definition of a local table contains the structure of the table only"

[ADLINGTON, Robert](https://jira.tools.sap/secure/ViewProfile.jspa?name=I063893) , maybe we could be more explicit, specifically for the documentation of the import to clearly indicate that only the table structure is imported and not any data from source tenant.
"

### Feedback Type (Optional)

None

### Page Title on SAP Help Portal (prefilled)

Exporting Content for Sharing with Other Tenants

### Page URL on SAP Help Portal (prefilled)

https://help.sap.com/docs/SAP_DATASPHERE/be5967d099974c69b77f4549425ca4c0/44e775c3b7d24d2483caaf02c598bc21.html

**Comment by CindyVenet** [comment]
Dear User
We’ve rewritten the whole “Overwrite Preferences” property in "Importing Content from Another Tenant" and added the “no data” note here and in other prominent places. These changes will be available in 2024.09.


![image](https://github.com/SAP-docs/sap-datasphere/assets/117640545/561a2efc-9e7a-4fc3-8187-270816668b00)


Thank you for the contribution 
best regards
Cindy for the UA team
