### ISSUE TITLE
Correction for link to data lake product page

### ISSUE THREAD

**Issue by JCurrie27** [SAP-docs/sap-datasphere#45]
### Issue description

The URL should be:
https://help.sap.com/docs/hana-cloud-data-lake 

### Feedback Type (Optional)

linking

### Page Title on SAP Help Portal (prefilled)

Integrating Data to and From SAP HANA Cloud Data Lake

### Page URL on SAP Help Portal (prefilled)

https://help.sap.com/docs/SAP_DATASPHERE/be5967d099974c69b77f4549425ca4c0/e84545bd205b4f9f9c1731144c7d3075.html?q=data%20lake

**Comment by co-sti** [comment]
Hello John, 
thanks a lot for your feedback. I've updated the link with the SAP Datasphere 2024.12 version. You can find the updated documentation soon in the internal preview for [Integrating Data to and From SAP HANA Cloud Data Lake](https://help.sap.com/docs/SAP_DATASPHERE/be5967d099974c69b77f4549425ca4c0/e84545bd205b4f9f9c1731144c7d3075.html?state=DRAFT&version=DEV).
Best Regards,
Conny (from the SAP Datasphere UA team)
