### ISSUE TITLE
Destination Type Note

### ISSUE THREAD

**Issue by LucimarM** [SAP-docs/sap-datasphere#46]
### Issue description

Hello
I got the following question from customer about the following scenarios, they are asking if there is any limitation:

1.Same hyperscaler but same regions (AWS Frankfurt and AWS Frankfurt).
2.Same hyperscaler and different regions (AWS Frankfurt and AWS Virginia).
3.Different hyperscaler and different regions (AWS Frankfurt and Azure Virginia).

Reading the documentation (below note), It is not clear and looks like its only possible to transport to tenants on the same region.

_Note: SAP Datasphere is only available on the Cloud Foundry platform. You can share to tenants that use the same type of Cloud Foundry data center as yours. These host systems use two digits, such as eu10 or us30._

I reached the developer to clarify which of those scenarios are supported. I got the following answer:

_ACN would support sharing of packages with all landscapes across hyper-scalers that allow sharing. For example, sharing between tenants on AWS, GCP and Azure are supported (EU10, US10, EU20, US20, US30, IN30…). 
Only restriction are on private/EU-access landscapes. 
-	Sharing with any landscape (EU10, US10, EU20, US20, US30, IN30…) and EU11 is not allowed
-	Sharing with NS2 landscapes are not allowed
-	Sharing with AliCloud is not allowed._

Could you improve the text of such note making it clear what is supported?

Best reards
Lucimar

### Feedback Type (Optional)

clarity

### Page Title on SAP Help Portal (prefilled)

Adding Sharing Destinations

### Page URL on SAP Help Portal (prefilled)

https://help.sap.com/docs/SAP_DATASPHERE/be5967d099974c69b77f4549425ca4c0/562e9969426840798e8a5bbf9c395ce8.html?version=cloud

**Comment by CindyVenet** [comment]
Dear user

thank you for your feedback. We are working on it and will come back soon with a solution

best regards
Cindy for the UA team

**Comment by CindyVenet** [comment]
Dear User,

Thanks for the input.

I’m guessing that you first bullet should read that sharing is supported for all these landscapes?
•	Sharing with any landscape (EU10, US10, EU20, US20, US30, IN30…) and EU11 is not allowed


Would this rewrite of the note work for you?
You can share with other SAP Datasphere tenants on any hyperscaler landscape that allows sharing. NS2 and AliCloud landscape do not allow sharing.
![image](https://github.com/SAP-docs/sap-datasphere/assets/117640545/2ffe3a3d-5b09-4db9-9058-d2ba71a98b16)


Thanks

**Comment by CindyVenet** [comment]
Hi 
I am closing this issue as no reaction since May 30. I guess issue is now solved
best regards
