### ISSUE TITLE
Privilege "Data Warehouse Data Integration"  with READ perimission is a GLOBAL privilege.

### ISSUE THREAD

**Issue by akarimb007** [SAP-docs/sap-datasphere#47]
### Issue description

Privilege "Data Warehouse Data Integration"  with READ perimission is a GLOBAL privilege.

For“creating DATA Product" from DataSharingcockpit >>"My Data Products”,  the developers would need below two roles:
1. DW scoped Modeler role plus
2. READ permission for GLOBAL privilege  "Data Warehouse Data Integration" .

As per SAP's documentation, privilege "Data Warehouse Data Integration"  with "READ" perimission is a SCOPED privilege.
Kindly check  and let us know.

### Feedback Type (Optional)

None

### Page Title on SAP Help Portal (prefilled)

Privileges and Permissions

### Page URL on SAP Help Portal (prefilled)

https://help.sap.com/docs/SAP_DATASPHERE/9f804b8efa8043539289f42f372c4862/d7350c6823a14733a7a5727bad8371aa.html

**Comment by CindyVenet** [comment]
Dear user

thank you for your feedback. We are having a look at it and will provide an answer soon.

best regards
cindy for the UA team

**Comment by CindyVenet** [comment]
Dear User, 

After a discussion with the development team, we can confirm that the privilege “Data Warehouse Data Integration” is a scoped privilege. 
The scoped role “DW Scoped Modeler” that is delivered with SAP Datasphere includes the “Data Warehouse Data Integration” scoped privilege with the Read permission.

Does this answer your question?

Thanks again for your feedback.
Cindy for the UA team
Best regards

**Comment by akarimb007** [comment]
Hi Cindy,

If I assign the scoped role “DW Scoped Modeler”, to a user – will he/she be able to create a DATA PRODUCT using “Data Sharing cockpit” ?

The answer is “NO”. We tested this scenario and realized that if we give Read permission for privilege “Data Warehouse Data Integration” at GLOBAL custom role, the user can create data product.

Attached an email for your reference.

Thanks
Anu

**Comment by CindyVenet** [comment]
Dear Customer, 

After discussing with the development team, we confirm that the privilege "Data Warehouse Remote Connection (CRUD--S-)" is required for the Data Marketplace. 

During the installation of a data product, a remote connection is established between the customer's target tenant (the one purchasing the product) and the data provider's source tenant.

The business user's ID is used to establish a remote connection in the selected target space. Therefore, the user installing a product needs this permission.

Does it help? I could not see your attached mail (I supposed that this is not supported by github)

best regards

**Comment by CindyVenet** [comment]
Dear user, 

To create a data product using the Data Sharing Cockpit, a user must have the scoped privilege “Data Warehouse Data Builder” with the permissions Create, Read and Update.

It would be interesting to view all the privileges and permissions that your user has.
Maybe, this is what you’ve included in the attached email, which unfortunately we were not able to see. Could you please send it again or send the whole list of privileges? 

thank you and best regards
cindy for the UA team

**Comment by akarimb007** [comment]
What privilege does a user need to   >>> Create a DATA PRODUCT using “Data Sharing cockpit” ?

**Comment by CindyVenet** [comment]
Dear user,

We’ve answered to this question in a previous email:
To create a data product using the Data Sharing Cockpit, a user must have the scoped privilege “Data Warehouse Data Builder” with the permissions Create, Read and Update.
You can find documentation on scope role under this link: https://help.sap.com/docs/SAP_DATASPHERE/9f804b8efa8043539289f42f372c4862/b5c4e0b6c462414783ebbfc053815521.html 

If this still does not help, it would be interesting to view all the privileges and permissions that your user has to identify the missing ones. 

Thank you and best regards
Cindy

**Comment by CindyVenet** [comment]
Hi 
Closing this ticket as no reaction from the customer. So I assume problem is now solved. 
best regards

**Comment by OliviaValeano** [comment]
[like]  VALEANO, Olivia reacted to your message:
________________________________
