### ISSUE TITLE
For App : (Data Marketplace) is the Privilege "Data Warehouse Remote Connection (CRUD--S-)" needed ?

### ISSUE THREAD

**Issue by akarimb007** [SAP-docs/sap-datasphere#48]
### Feedback Type (Optional)

None

### Page Title on SAP Help Portal (prefilled)

Roles and Privileges by App and Feature

### Page URL on SAP Help Portal (prefilled)

https://help.sap.com/docs/SAP_DATASPHERE/9f804b8efa8043539289f42f372c4862/2d8b7d04dcae402f911d119437ce0a74.html

**Comment by CindyVenet** [comment]
Dear user

Thank you for your feedback. We're looking at the issue and will provide an answer soon. 

best regards
Cindy
