### ISSUE TITLE
No option to export or copy paste the information on "Authorization Overview" page

### ISSUE THREAD

**Issue by akarimb007** [SAP-docs/sap-datasphere#49]
### Issue description

No option to export or copy paste the information on "Authorization Overview" page

### Feedback Type (Optional)

None

### Page Title on SAP Help Portal (prefilled)

View Authorizations (Users, Roles and Spaces)

### Page URL on SAP Help Portal (prefilled)

https://help.sap.com/docs/SAP_DATASPHERE/9f804b8efa8043539289f42f372c4862/c6538ea2db884e599072e62bdb03e68c.html

**Comment by CindyVenet** [comment]
Dear User

thank you for your feedback. We are working on it and will provide an answer soon

best regards
Cindy for the UA team

**Comment by CindyVenet** [comment]
Dear user

Thanks for your feedback. It seems to us that this is not related to documentation, but this is a feature that you’d like to be offered in the page “Authorization Overview”. Did we understand correctly?
If not, could you please clarify your question or feedback.

Best regards
Cindy

thank you and best reg

**Comment by akarimb007** [comment]
Yes Cindy.

I meant, there is no option to extract the data from “Authorization Overview” page.
We cannot select any content on this page.

Thanks
Anu

**Comment by CindyVenet** [comment]
Dear User
Thank you for your confirmation. User Assistance can't unfortunately help as it does not relate to the content we've provided in terms of documentation.  It's a development request to be sent to the development team. 
Best regards
Cindy for the UA team
