### ISSUE TITLE
Missing the scoped roles in this page

### ISSUE THREAD

**Issue by akarimb007** [SAP-docs/sap-datasphere#50]
### Issue description

Issue:
SCOPED Privilege and Scoped roles to Apps and feature is missing in the following page:

https://help.sap.com/docs/SAP_DATASPHERE/9f804b8efa8043539289f42f372c4862/2d8b7d04dcae402f911d119437ce0a74.html

With Scoped privilege already in-place and use, it would be helpful to have the SCOPED privilege and role mapping to Apps and features.
Currently, this page has no scoped role mapped to any of apps.

### Feedback Type (Optional)

None

### Page Title on SAP Help Portal (prefilled)

Roles and Privileges by App and Feature

### Page URL on SAP Help Portal (prefilled)

https://help.sap.com/docs/SAP_DATASPHERE/9f804b8efa8043539289f42f372c4862/2d8b7d04dcae402f911d119437ce0a74.html

**Comment by CindyVenet** [comment]
Dear SAP user

we are looking at the issue and will come back with a solution soon.

Thank you for your help
best regards
Cindy for the UA team

**Comment by CindyVenet** [comment]
« Dear user, 

Thanks for your feedback on this page.
The goal of the page is to list all apps and tools and mention for each, which privileges give access to it.
On the other hand, scoped privileges are listed here, where we clearly differentiate global privileges and scoped privileges: https://help.sap.com/docs/SAP_DATASPHERE/9f804b8efa8043539289f42f372c4862/d7350c6823a14733a7a5727bad8371aa.html
The 2 pages are complementary. 

You say “this page has no scoped role mapped to any of apps”. The 3rd column actually lists the role templates that grant the privileges listed in the 2nd column. Please note that a scoped role inherits the privileges that are included in its role template and we mention the role templates in the 3rd column.

This is how we can read the table: in the example below, we say that the DW Modeler and DW Space Administrator role templates grant the privilege Data Warehouse Data Builder privilege (which is a scoped privilege, as indicated in the page https://help.sap.com/docs/SAP_DATASPHERE/9f804b8efa8043539289f42f372c4862/d7350c6823a14733a7a5727bad8371aa.html). 
Besides, to grant privileges to users in spaces, you need to a create scoped role (as explained in this page https://help.sap.com/docs/SAP_DATASPHERE/9f804b8efa8043539289f42f372c4862/b5c4e0b6c462414783ebbfc053815521.html). 
![image](https://github.com/SAP-docs/sap-datasphere/assets/117640545/90e397db-a17e-46b7-8d3b-08fd8b4b0435)
I hope this helps. 

Best regards
Cindy for the UA team
