### ISSUE TITLE
JDBC is supported in OpenSQL Schema? 

### ISSUE THREAD

**Issue by ismael-cardoso** [SAP-docs/sap-datasphere#52]
### Issue description

In https://help.sap.com/docs/SAP_DATASPHERE/43509d67b8b84e66a30851e832f66911/4db6f5a329af44509ae422ad707877b2.html?locale=en-US, there is no mentioning of JDBC.

How customers are suppose to do this integration? There is no available guide for that. 

### Feedback Type (Optional)

None

### Page Title on SAP Help Portal (prefilled)

Connect to Your Open SQL Schema

### Page URL on SAP Help Portal (prefilled)

https://help.sap.com/docs/SAP_DATASPHERE/be5967d099974c69b77f4549425ca4c0/b78ad208f8c4494489aabf97284679b6.html

**Comment by CindyVenet** [comment]
Hi Ismael
Thank you for your feedback. We are working on it and will be back soon.
best regards
cindy

**Comment by CindyVenet** [comment]
Dear User
We have updated the documentation:
-	Have retitled the topic to [Consume Data in Power BI and Other Clients, Tools, and Apps via ODBC/JDBC](https://help.sap.com/docs/SAP_DATASPHERE/43509d67b8b84e66a30851e832f66911/4db6f5a329af44509ae422ad707877b2.html)
-	Have a link to [Connect to SAP HANA Cloud via JDBC](https://help.sap.com/docs/hana-cloud/sap-hana-cloud-getting-started-guide/connect-to-sap-hana-database-in-sap-hana-cloud-via-jdbc)
-	Mention ODBC/JDBC everywhere where we used to say just ODBC

thank you and best regards
Cindy for the UA team
