### ISSUE TITLE
Feedback for "Standard Application Roles"

### ISSUE THREAD

**Issue by MartinSautterAnalytics4you** [SAP-docs/sap-datasphere#9]
https://help.sap.com/docs/SAP_DATASPHERE/9f804b8efa8043539289f42f372c4862/a50a51d80d5746c9b805a2aacbb7e4ee.html?locale=en-US

Confusing , old version, Update the Role names its now SAP Datasphere Integrator ....

**Comment by CindyVenet** [comment]
Dear SAP Datasphere user

Thanks for your feedback. We are aware of this difference and this will soon be fixed.

Best regards
Cindy
